include: package:lints/recommended.yaml

analyzer:
  exclude:
    - flutter/*

linter:
  rules:
    - prefer_single_quotes
    - avoid_returning_null_for_future
    - prefer_void_to_null
    - always_require_non_null_named_parameters
    - avoid_returning_null
    - avoid_returning_null_for_void
    - prefer_initializing_formals
    - prefer_typing_uninitialized_variables
    - avoid_print
    - prefer_final_locals
    - require_trailing_commas
    - sort_constructors_first
